CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA;
USE BD_BIBLIOTECA; 

CREATE TABLE IF NOT EXISTS AUTOR(
CPF VARCHAR(14) PRIMARY KEY,
QUANTIDADE_LIVROS INTEGER NOT NULL,
FOTO BLOB NOT NULL,
NOME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
AVALIACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE,
    FOTO BLOB NOT NULL,
    AVALIACAO VARCHAR(255),
    FK_AUTOR_CPF VARCHAR (14) NOT NULL,
    FOREIGN KEY (FK_AUTOR_CPF) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIVRO_ACESSADO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	FK_LIVRO_DIGITAL_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_LIVRO_DIGITAL_ID) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FK_LEITOR_CPF VARCHAR (14) NOT NULL,
    FOREIGN KEY (FK_LEITOR_CPF) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);