CREATE DATABASE IF NOT EXISTS BD_ENQUESTES;
USE BD_ENQUESTES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR (255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR (500),
    USU_PROFISSAO VARCHAR (200),
    USU_AREA_FORMACAO VARCHAR (500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIUVO") NOT NULL,
    USU_ESTADO VARCHAR (2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MEDIO","SUPERIRO") NOT NULL,
    USU_EMAIL VARCHAR (255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR (255) NOT NULL,
    USU_NOME VARCHAR (255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);
CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
	ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR (500) NOT NULL,
    ENQ_NOME VARCHAR (255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL, 
    PRIMARY KEY (ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);
    
CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
	FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
	FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);
    
CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
	RES_DESCRICAO VARCHAR (255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);


SELECT * FROM USUARIO;

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC,USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,
USU_EMAIL,USU_SENHA, USU_NOME)
VALUES ("2025-10-31", "Ruan_Mendes", "Administrador", "Administração", "Administração", "2005-11-5", "SOLTEIRO", "SP", "MEDIO", "RuanMendes@gmail.com", "123456", "Ruan Mendes");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC,USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,
USU_EMAIL,USU_SENHA, USU_NOME)
VALUES ("2025-11-12", "Sophia_Peron", "Medica", "Medicina", "Medicina", "2009-05-15", "SOLTEIRO", "SP", "SUPERIRO","SophiaPeron@gmail.com", "9876543", "Sophia peron");


INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC,USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,
USU_EMAIL,USU_SENHA, USU_NOME)
VALUES ("2027-02-22", "Leliani_Ribeiro", "pscanalista", "terapeuta", "Psicanalise", "1979-09-03", "CASADO", "SP", "SUPERIRO","LelianiRibeiro@gmail.com", "201918","leliani Ribeiro");

  INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-11-05", "2025-10-01", "Você gosta de sushi?", "Comida","1");  

INSERT INTO ENQUETE   (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-11-05", "2025-10-01", "Qual é a cor do céu?", "Cores", "3");

INSERT INTO ENQUETE   (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-11-05", "2025-10-01", "Qual rede social vc mais usa?", "Internet", "2");

	

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "2", "1");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "1", "3");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "3", "2");

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Enquete das cores", "2");

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Enquete das comidas", "1");

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Enquete das redes sociais", "3");

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Enquete das redes sociais", "3");

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("A = azul ", "A", "3");

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("B = amarelo", "A", "3");

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("C = vermelho", "A", "3");
