CREATE DATABASE IF NOT EXISTS BD_GESTAO_PROJETOS;
USE BD_GESTAO_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESCRICAO VARCHAR(200),
    NOME VARCHAR(255) NOT NULL,
    ORCAMENTO VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FUNCAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(100),
	FK_PROJETOS_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_PROJETOS_ID) REFERENCES PROJETOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	FK_FUNCIONARIO_CPF VARCHAR(14),
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    FK_TAREFA_ID INTEGER,
    FOREIGN KEY (FK_TAREFA_ID) REFERENCES TAREFA(ID) ON DELETE CASCADE
);
