CREATE DATABASE IF NOT EXISTS BD_MUSICA_2ANO;
USE BD_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    FOTOS BLOB,
    DESCRICAO VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS GENERO(
	 NOME VARCHAR(30) PRIMARY KEY,
     DESCRICAO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER PRIMARY KEY,
    FOTO BLOB NOT NULL,
    NOME VARCHAR(255),
    AVALIACAO VARCHAR(255),
    FK_ARTISTA_CPF VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    DURACAO VARCHAR(255),
    LETRA VARCHAR(2400),
    FK_ALBUM_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID),
    FK_GENERO_NOME VARCHAR(30) NOT NULL,
    FOREIGN KEY (FK_GENERO_NOME) REFERENCES GENERO(NOME)
);