CREATE DATABASE IF NOT EXISTS BD_CONSULTA;
USE BD_CONSULTA;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);


CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    FK_CRM_MEDICO VARCHAR(20) NOT NULL,
	FK_CPF_PACIENTE VARCHAR(14) NOT NULL,
    FOREIGN KEY(FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FOREIGN KEY(FK_CPF_PACIENTE)REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);