CREATE DATABASE IF NOT EXISTS BD_RESERVAS_HOTEL;
USE BD_RESERVAS_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO INTEGER NOT NULL,
    FOTO BLOB NOT NULL,
    FK_HOTEL_CNPJ VARCHAR (20) NOT NULL,
    FOREIGN KEY (FK_HOTEL_CNPJ) REFERENCES HOTEL(CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESERVADO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_QUARTO_ID INTEGER  NOT NULL,
    FOREIGN KEY (FK_QUARTO_ID) REFERENCES QUARTO(ID) ON DELETE CASCADE,
    FK_HOSPEDE_CPF VARCHAR (14) NOT NULL,
    FOREIGN KEY (FK_HOSPEDE_CPF) REFERENCES HOSPEDE(CPF) ON DELETE CASCADE
);