CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AERIAS;
USE BD_RESERVAS_AERIAS;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
	CPF VARCHAR (14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS VOO(
	CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    COMPANHIA VARCHAR (255) NOT NULL,
    DATA_VOO DATE NOT NULL,
    QUANTIDADE_PASSAGEIROS INTEGER,
    QUANTIDADE_ASSENTOS INTEGER
);

CREATE TABLE IF NOT EXISTS ASSENTOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO INTEGER  NOT NULL,
    VALOR INTEGER  NOT NULL,
    FK_PASSAGEIROS_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_PASSAGEIROS_CPF) REFERENCES PASSAGEIROS(CPF),
    FK_VOO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_VOO_ID) REFERENCES VOO(CODIGO)
);