CREATE DATABASE IF NOT EXISTS BD_STREAMING_VIDEO;
USE BD_STREAMING_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_NASCIMENTO DATE NOT NULL,
    DESCRICAO VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEMPO VARCHAR(255),
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VIZUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERARACAO VARCHAR(1000),
     FK_VIDEO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO(ID) ON DELETE CASCADE
);

