SELECT * FROM SUPERMERCADO;

/* 
CONSULTAR O AUMENTO DE R$ 2,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL >= R$ 5,00
*/
SELECT PRO_NOME AS "NOME", PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS", PRO_PRECO AS "PREÇO ATUAL", TRUNCATE ((PRO_PRECO + 2),2) AS "PREÇO COM AJUSTE DE 2" FROM PRODUTO
WHERE PRO_PRECO >= 5;