CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE_2ANO;
USE BD_GESTAO_ESTOQUE_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    AVALIACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(300) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    VALOR DOUBLE NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS FORNECIMENTO(
	ID INTEGER PRIMARY KEY,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID),
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ),
    FK_FORNECEDOR_CNPJ VARCHAR(20) NOT NULL
);